### PR TITLE
Fix regular expressions with /[^]/

### LINKED ISSUE #146: ParserException: InvalidRegularExpression on valid regex
Regular expression literal:
```js
/(?:\s|\/\/.*|\/\*[^]*?\*\/)*/g
```

Source `@babel\parser\lib\index.js`
```js
const skipWhiteSpace = /(?:\s|\/\/.*|\/\*[^]*?\*\/)*/g;  
```

[index.zip](https://github.com/sebastienros/esprima-dotnet/files/5966005/index.zip)

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #146

### CODE REVIEW

File: src/Esprima/Scanner.cs [hunk 1]
```diff
@@ -1549,6 +1549,13 @@ public Token ScanTemplate()
                 tmp = Regex.Replace(tmp, "[\uD800-\uDBFF][\uDC00-\uDFFF]", astralSubstitute);
             }
 
+            // .NET doesn't support [^] which is equivalent to `[^.]`
+            // c.f. https://github.com/sebastienros/esprima-dotnet/issues/146
+            if (tmp.Contains("[^]"))
```
Comment (lahma) [inline src/Esprima/Scanner.cs:1554]: not sure if calling Replace directly is much different, search must be done again

**Review by lahma — APPROVED** [review]

File: src/Esprima/Scanner.cs (hunk 1 above)
Comment (sebastienros) [reply src/Esprima/Scanner.cs:1554]: I just checked and it looks like it's allocating in all cases. https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs#L1042

It's probably insignificant, but I think we can keep the test then.

Comment (lahma) [reply src/Esprima/Scanner.cs:1554]: Sure, I was just wondering.
