### PR TITLE
Fix multi-line comment scanning

### LINKED ISSUE #137: System.NullReferenceException when scanning comments in v1.0.1270
The code
 ```csharp
    var scanner = new Scanner("var foo=1; /* \"330413500\" */", new ParserOptions {Comment = true, Loc = true});
    Token token;
    do
    {
        foreach (var comment in scanner.ScanComments())
            Console.WriteLine($"{comment.Start}-{comment.End}");
        token = scanner.Lex();
    } while (token.Type != TokenType.EOF);
 ```

works with Esprima v1.0.1258 (prints `11-28`) and doesn't work with v1.0.1270 where the exception is thrown:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Esprima.Scanner.SkipMultiLineComment() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 317
   at Esprima.Scanner.ScanCommentsInternal() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 425
   at Esprima.Scanner.ScanComments() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 383
   at ConsoleApp1.Program.Main(String[] args) in C:\sandbox\EsprimaCheck\ConsoleApp1\Program.cs:line 15
```

### PR DESCRIPTION
**Pull request by lahma**
Nullable annotations were yelling that this is a bad idea, and it was. 

Original code used to just set line and column but the real problem was that different data structures were used than in original Esprima. Changed to follow the same format for scanner structures as in JS version:

https://github.com/jquery/esprima/blob/45c9ab14d96f7f7fa88333fdd897487a8c20082f/src/scanner.ts#L15-L31

fixes #137

### CODE REVIEW

File: src/Esprima/Utils/AstJson.cs [hunk 1]
```diff
@@ -168,30 +168,30 @@ void WriteLocationInfo(Node node)
                 {
                     if (includeRange)
                     {
-                        writer.Member("range");
```
Comment (lahma) [inline src/Esprima/Utils/AstJson.cs:171]: compiler issued a warning as the member field is checked against null but the parameter is not (these use parameter event though member has been initialized)

File: src/Esprima/Marker.cs [hunk 2]
```diff
@@ -0,0 +1,20 @@
+namespace Esprima
+{
+    public class Marker
```
Comment (atifaziz) [inline src/Esprima/Marker.cs:3]: This doesn't need to be public.

**Review by atifaziz — CHANGES_REQUESTED** [review]

File: src/Esprima/Marker.cs (hunk 2 above)
Comment (lahma) [reply src/Esprima/Marker.cs]: Made it internal, good catch

**Review by atifaziz — APPROVED** [review]
