### PR TITLE
Preventing stack-overflow exceptions

### LINKED ISSUE #104: StackOverflowException when parsing a lot of starting parentheses
See https://github.com/sebastienros/jint/issues/572

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #104

### CODE REVIEW

File: src/Esprima/JavascriptParser.cs [hunk 1]
```diff
@@ -1847,10 +1847,18 @@ private ParsedParameters ReinterpretAsCoverFormalsList(INode expr)
...
+        private const int MaxAssignmentDepth = 100;
+        private int _assignmentDepth = 0;
+
         private Expression ParseAssignmentExpression()
         {
             INode expr;
 
+            if (_assignmentDepth++ > MaxAssignmentDepth)
+            {
+                ThrowUnexpectedToken(_lookahead, "Maxinimum statements depth reached");
```
Comment (lahma) [inline src/Esprima/JavascriptParser.cs]: Typo *Maxinimum*
